### ISSUE TITLE
getHomeDirectory on POSIX systems is unreliable

### ISSUE THREAD

**Issue by hasufell** [haskell/directory#102]
https://github.com/haskell/directory/blob/b3184cabb8c6a90eec7e921d6ca5058d57da3d82/System/Directory/Internal/Posix.hsc#L283-L284

strikes me as a naive implementation. [POSIX](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html) doesn't say that `$HOME` is mandatory to be set. The wording is:

> If the variables in the following two sections are present in the environment during the execution of an application or utility, they shall be given the meaning described below.

Even worse, `getHomeDirectory` will **error** when this optional environment variable is not set.

A better way of doing this would be:

* if $HOME is set in the environment, return it
* if $HOME is not set in the environment, look up `getpwuid(getuid())->pw_dir`, see [getpwuid](https://pubs.opengroup.org/onlinepubs/009695399/functions/getpwuid.html) (or rather `getpwuid_r` for thread-safety)
* if none are set, raise an error

Inspecting other popular standard library language functions, they seem to do exactly that:

* https://doc.rust-lang.org/std/env/fn.home_dir.html
* https://docs.python.org/3/library/os.path.html#os.path.expanduser

The only thing that is debatable about this is how an *empty* and *set* `$HOME` will be treated.

**Comment by Rufflewind** [comment]
This was resolved by https://github.com/haskell/directory/pull/103.
