### ISSUE TITLE
Function which uses types to indicate directory or files

### ISSUE THREAD

**Issue by Boarders** [haskell/directory#105]
It would be nice to have a function like:

```haskell
listDirectoryEither :: FilePath -> IO [Either FilePath FilePath]
```
In this function all subdirectories in the directory would be returned as `Left dir` and all files would be returned as `Right file`. This can easily be done using the functions already available in the library but I frequently enough want to use this pattern that it would be nice if it were part of the library. This same pattern is also used by streamly (see [here](https://github.com/composewell/streamly/blob/d7d42be739da95069d37914cd48b31be82672791/src/Streamly/Internal/FileSystem/Dir.hs#L242)) for example. I am happy to make a pull request adding this function though the version I write will simply combine `listDirectory` and `doesDirectoryExist` which may not be the best performance possible.

**Comment by cartazio** [comment]
A concrete implementation  is often the best way to get a conversation
started.  At least naively this sounds like an easy yes.

**Comment by Boarders** [comment]
Here is a simple version:
```haskell
listDirectoryEither :: FilePath -> IO [Either FilePath FilePath]
listDirectoryEither path = listDirectory path >>= traverse label
  where
    label :: FilePath -> IO (Either FilePath FilePath)
    label p =
      do
        b <- doesDirectoryExist p
        pure $ if b then Left p else Right p
```

**Comment by chessai** [comment]
I like this. Perhaps you could prepare a PR?

**Comment by Boarders** [comment]
Could someone possibly give me some hints on what tests I might need to add. The testing framework is currently beyond me.

**Comment by cartazio** [comment]
we that once you throw up the PR, its easier in that interface  :)

**Comment by Rufflewind** [comment]
Thanks for filing this issue.  Before we begin the PR process, I think there are some design issues that should be resolved first.

 1. The type `[Either FilePath FilePath]` is rather difficult to read -- which one is `Left` and which one is `Right`?

 2. Another orthogonal concern: I think `([FilePath], [FilePath])` is probably more convenient for the user than `Either [FilePath] [FilePath]`.

 3. Do "directories" include directory symbolic links?  If symlinks are included as directory, it may cause infinite recursion.

 4. The implementation in https://github.com/haskell/directory/issues/105#issuecomment-581985623 is non-atomic and may crash or return stale information.

I believe a more robust implementation should take advantage of OS-specific APIs like [`readdir`](http://man7.org/linux/man-pages/man3/readdir.3.html) and [`FindFirstFileW`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfilew).  Other languages have built wrappers around them and I think it would be great if `directory` exposed something similar in power.  A `readdir`-like API should ideally return as much information as the underlying OS API provides, not just whether the entry is a directory or not.

Some prior art that would be useful to follow:

* [`os.scandir` in Python](https://docs.python.org/3/library/os.html#os.scandir)
* [`std::fs::ReadDir` in Rust](https://doc.rust-lang.org/std/fs/struct.ReadDir.html)

**Comment by Boarders** [comment]
@Rufflewind : That is all reasonable, ideally we would get back all the information in something like `dirent` or similar directly from the filestream. I think such a re-design also prompts other questions (like continuing to use `type FilePath = String`). Regardless, I think given this, the issue can probably be closed as I don't really have the know-how of OS specifics (nor for writing an atomic/safe version which is again probably easiest if given access to the file stream though I can't say I know) to put together a reasonable proposal on a way forward.

**Comment by Rufflewind** [comment]
Thanks. Closing as requested.
