### ISSUE TITLE
Accommodate time 1.11

### ISSUE THREAD

**Issue by chris-martin** [haskell/directory#115]
This seems to already be done, so I wonder if it might be released? https://github.com/haskell/directory/commit/0633b48b010093f64f98ee494265436e96456aed

**Comment by chris-martin** [comment]
`base-4.15` also seems to be accommodated, just not released.

**Comment by Rufflewind** [comment]
Per https://github.com/haskell-infra/hackage-trustees/blob/master/cookbook.md#the-correct-way, I relaxed the bounds by editing the Hackage for http://hackage.haskell.org/package/directory-1.3.6.1:

```diff
# https://github.com/haskell/directory/commit/0633b48b010093f64f98ee494265436e96456aed
- time >=1.4 && <1.11
+ time >=1.4 && <1.12

# https://github.com/haskell/directory/commit/cecf363bc07004ad314e0297ce34ddba05031c0e
- Win32 >=2.2.2 && <2.9
+ Win32 >=2.2.2 && <2.11

# https://github.com/haskell/directory/commit/49d274dad953db62bc9a634f68cf1b0c5fcbb22c
- base >=4.5 && <4.15
+ base >=4.5 && <4.16
```

Is that sufficient?

**Comment by chris-martin** [comment]
Works for me! Thank you :heart:
