### ISSUE TITLE
AppVeyor and Travis CI integration are no longer necessary

### ISSUE THREAD

**Issue by Rufflewind** [haskell/directory#120]
To @hvr or anyone with access to the *Settings* panel for https://github.com/haskell/directory:

Would you mind disabling both AppVeyor and Travis CI integration with the haskell/directory repo? See *Settings -> Web Hooks*, as well as *Settings -> Integrations*, if there's anything applicable. This would suppress any false errors caused by the absence of AppVeyor and Travis CI configs.

Source for context: https://github.com/haskell/directory/pull/118, https://github.com/haskell/directory/commit/aab4f6b87e002116aa86934ead2260b9ac2fe60d

**Comment by RyanGlScott** [comment]
I've removed the Travis and AppVeyor web hooks from the Settings page. (Travis is also listed in the Integrations page, but there's no option for me to remove it.) Does that fix the issue?

**Comment by Rufflewind** [comment]
Thanks, that fixed it!
