### ISSUE TITLE
A release, please?

### ISSUE THREAD

**Issue by athas** [haskell/directory#122]
I'd like to make use of #121 in some [ongoing work on cabal](https://github.com/haskell/cabal/pull/7386), but it's not part of any release.  I also can't just add a source-package to `cabal.project` referencing a commit, as `directory` needs manual preprocessing (`autoreconf -fi`), which I don't think cabal supports.

**Comment by Rufflewind** [comment]
Created: https://hackage.haskell.org/package/directory-1.3.7.0
