### ISSUE TITLE
Function to find executable scripts (not .exe) on PATH (cygwin) 

### ISSUE THREAD

**Issue by andreasabel** [haskell/directory#123]
It seems like `findExecutable` does not deliver executable files not ending in `.exe` on cygwin.
```
$ cabal info directory
* directory        (library)
    Synopsis:      Platform-agnostic library for filesystem operations
    Versions installed: 1.3.6.0

$ ls $(which gzip)*
/usr/bin/gzip.exe*

$ ls $(which gunzip)*
/usr/bin/gunzip*

$ ghci
GHCi, version 8.10.3: https://www.haskell.org/ghc/  :? for help

Prelude> :m + System.Directory

Prelude System.Directory> findExecutable "gzip"
Just "C:\\cygwin64\\bin\\gzip.exe"

Prelude System.Directory> findExecutable "gunzip"
Nothing
```
So, binaries like `gzip.exe` are found, but scripts like `gunzip` not.

I suppose this makes some sense, because `callProcess` cannot execute scripts directly:
```
Prelude System.Process> callProcess "gzip" ["-h"]
Usage: gzip [OPTION]... [FILE]...

Prelude System.Process> callProcess "gunzip" ["-h"]
*** Exception: gunzip: callProcess: does not exist (No such file or directory)

Prelude System.Process> callProcess "sh" ["-c", "gunzip -h"]
Usage: gzip [OPTION]... [FILE]...
```
Scripts can only be executed via `sh` on cygwin.  (This is different on macOS, for instance, where they can be launched directly via `callProcess` and are also found by `findExecutable`.)

It would be helpful to have functionality to find scripts that can be executed via `sh` (so, marked as executable) on the PATH.  Or is there another convenient and portable way to probe for the existence of an executable script without trying to run it?

**Comment by Rufflewind** [comment]
>     Prelude System.Directory> findExecutable "gzip"
>     Just "C:\\cygwin64\\bin\\gzip.exe"

If you are seeing this, this likely means you are using the native Windows Haskell toolchain. *Programs built with the native Windows toolchain are not compatible with Cygwin.* The executability on shell scripts is a concept that only the Cygwin runtime understands; native Windows binaries are not linked to the Cygwin runtime (cygwin1.dll).

Cygwin is considered its own platform -- one may treat it as a *nix variant in some respects -- so `directory` might work on Cygwin if one were to compile using a Cygwin-compatible GHC. Unfortunately, I don't think [GHC is supported on Cygwin anymore](https://gitlab.haskell.org/ghc/ghc/-/wikis/building/windows/cygwin), and consequently, I don't think any Haskell packages are going to support Cygwin either. Sorry.

(Personally, I used to use Cygwin for dev work on Windows, but nowadays I find WSL a much smoother experience. For building native Windows applications, MSYS2-mingw64 works pretty well.)

**Comment by andreasabel** [comment]
Thanks for your advice @Rufflewind; I am rather inexperienced when it comes to Windows programming.  My goal is to support the [platforms that are available on github actions](https://github.com/actions/virtual-environments), named `ubuntu`, `macOS`, and `windows`.  Hearing that Cygwin is considered its own platform, it makes sense for me to abandon it (and not using it to test my solutions).

Stepping back a bit, I am looking for _X_ completing the following picture:
1. `callProcess "cmd" ["arg1",..."argn"]` can run iff `findExecutable "cmd"` returns `Just{}`.
2. `callCommand "cmd arg1 ... argn"` can run iff _X_.

It seems that e.g. on `macOS` _X_ is also `findExecutable "cmd"`, but I wonder how it looks on the other platforms.

**Comment by Rufflewind** [comment]
`callCommand` invokes the shell (which varies by platform and system configuration), so `cmd arg1 ... argn` can be any valid shell code, and not necessarily a single statement. If the shell is, say, of the Bourne family (e.g. Bash), you can write complex things like `for x in 1 2 3; do echo "hello world ${x}"; done`.

For a [simple command](https://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html#tag_02_09_01) like `foo bar`, a Bourne-family shell can accept [several things](https://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html#tag_02_09_01_01), such as:

1. A binary invocation: `foo` might refer to a binary on `PATH`, such as `/usr/bin/foo`.
2. A shell built-in: `foo` might be a built-in command in the shell interpreter. For example, `echo` is usually a built-in (distinct from `/usr/bin/echo`).
3. A shell function: `foo` might be some user-defined shell function,`foo() { ... }`.
4. A shell alias: The user may have defined an alias, like `alias foo=/usr/bin/cat`.

Beyond that there are non-Bourne shells like (t)csh, fish, Command Prompt, etc, which likely have their own criteria for what is considered a valid simple command.

**Comment by andreasabel** [comment]
Thanks @Rufflewind.  

I should relativize my spec

>     2\. `callCommand "cmd arg1 ... argn"` can run iff _X_.

to `cmd`s which are files on the `PATH`.  Of course, `for`-loops and other shell-expressions are out of scope.

But I agree to close this issue now, more research is needed first on what could be expected from such a function.
