### ISSUE TITLE
removeDirectoryRecursive failures on Windows

### ISSUE THREAD

**Issue by sjakobi** [haskell/directory#129]
I've been encountering this issue in CI jobs for `dhall-haskell` (https://github.com/dhall-lang/dhall-haskell/issues/2336). The failures look like this:

```
C:\Users\runneradmin\AppData\Local\Temp\stack-eadfc3912a464ffd\pretty-simple-4.0.0.0\.stack-work\dist\274b403a\setup: removeDirectoryRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:removePathRecursive:removeContentsRecursive:RemoveDirectory "\\\\?\\C:\\Users\\runneradmin\\AppData\\Local\\Temp\\stack-eadfc3912a464ffd\\pretty-simple-4.0.0.0\\.stack-work\\dist\\274b403a\\setup": unsatisfied constraints (The directory is not empty.)
```

Similar failures were reported in https://github.com/haskell/cabal/issues/7240. A fix was proposed for `Win32` in https://github.com/haskell/win32/pull/129, but rejected. Is this something that could be fixed in `directory`?!

**Comment by sjakobi** [comment]
I'm still getting these failures.

@Rufflewind What do you think about this issue?

**Comment by Rufflewind** [comment]
- Is this different from https://github.com/haskell/directory/issues/110?
- Do you have a CI script that can reproduce the issue with high probability?

**Comment by Rufflewind** [comment]
There's some ideas thrown around in #110 but I'm not aware of an easy fix on this issue. The lack of a reliable means reproduce this bug doesn't help.

The current known workaround is to retry on Windows. The number of retries may depend on the quantity of files you're deleting as well as the speed of the machine.
