### ISSUE TITLE
renameFile across drives fails on windows

### ISSUE THREAD

**Issue by Jashweii** [haskell/directory#132]
On windows you will get an error renaming a file from one drive to another with renameFile.

https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefileexa
Says that the flag MOVEFILE_COPY_ALLOWED must be used for this (which will copy/delete instead in this case)
The docs say MOVEFILE_REPLACE_EXISTING is used. 
I don't know if the copy/delete behaviour is acceptable, if it is presumably `MOVEFILE_COPY_ALLOWED | MOVEFILE_REPLACE_EXISTING` should be used, if not it would be nice if the docs said this won't work across drives on windows.

I originally hit this issue using ghcup, which I believe (due to the same exception) is from renameFile. Example in GHCI:
```
ghci> writeFile "C:\\test\\test.txt" "some text"
ghci> renameFile "C:\\test\\test.txt" "D:\\test.txt"
*** Exception: C:\test\test.txt: renameFile:renamePath:MoveFileEx "\\\\?\\C:\\test\\test.txt" Just "\\\\?\\D:\\test.txt": unsupported operation (The system cannot move the file to a different disk drive.)
ghci> renameFile "C:\\test\\test.txt" "C:\\test\\test2.txt" 
```
(The last rename works fine)

**Comment by Rufflewind** [comment]
`renameFile` is a low-level function that, by design, does not work across drives / devices / mount points. It is supposed to be cheap and (quasi)atomic, similar to a POSIX [rename](https://pubs.opengroup.org/onlinepubs/9699919799/functions/rename.html).

If you are looking to rename across devices, consider using `copyFileWithMetadata` and `removeFile`. There might be higher-level packages out there that let you do this more effortlessly.

**Comment by Jashweii** [comment]
> `renameFile` is a low-level function that, by design, does not work across drives / devices / mount points. It is supposed to be cheap and (quasi)atomic, similar to a POSIX [rename](https://pubs.opengroup.org/onlinepubs/9699919799/functions/rename.html).
> 
> If you are looking to rename across devices, consider using `copyFileWithMetadata` and `removeFile`. There might be higher-level packages out there that let you do this more effortlessly.

I will make an issue on ghcup's tracker, I just raised here for clarification. I guess this is already in the docs as it says "renaming across different physical devices" doesn't need to be supported.
