### ISSUE TITLE
Release for GHC 9.4.1

### ISSUE THREAD

**Issue by bgamari** [haskell/directory#141]
We are quickly approaching the final GHC 9.4.1 release. A prompt release to Hackage would be appreciated.

**Comment by Rufflewind** [comment]
According to the GHC tree,

- base 4.17
- time 1.12.2
- filepath 1.4.2.2
- Win32 2.12.0.0
- unix 2.7.2.2

It looks like the upper bound for base needs to be bumped to `<4.18`. Does that look right?

**Comment by bgamari** [comment]
Correct.

**Comment by Rufflewind** [comment]
https://hackage.haskell.org/package/directory-1.3.7.1
