### ISSUE TITLE
Unhelpful error with `copyFile` into non-existent directory

### ISSUE THREAD

**Issue by santiweight** [haskell/directory#144]
When copying a file `foo` into directory `bad_dir` that doesn't exist using `copyFile`, I get the following error:

```haskell
import System.Directory

main = do
  copyFile "bar.txt" "bad/bar.txt"
```

```
bad_dir: copyFile:atomicCopyFileContents:withReplacementFile:openBinaryTempFile: does not exist (No such file or directory)
```

Which is a little hard to stomach :laughing: thoughts?

**Comment by Rufflewind** [comment]
The failing entity is described in the message:

    bad_dir: copyFile:atomicCopyFileContents:withReplacementFile:openBinaryTempFile: does not exist (No such file or directory)
    ^^^^^^^
      This is the path to the thing that doesn't exist.

Does that make sense? Or is there a specific improvement you are looking for?

Note that in general `directory` does not control the phrasing of the underlying error. Errors are bubbled up from the underlying runtime / platform, and directory merely prepends annotations like `copyFile:atomicCopyFileContents:withReplacementFile:openBinaryTempFile:` as a form stack trace.

**Comment by Rufflewind** [comment]
Let me know if there are any other questions.
