### ISSUE TITLE
Updating the CI and the cabal file

### ISSUE THREAD

**Issue by Kleidukos** [haskell/directory#148]
Hi @Rufflewind!

I'd like to update the CI of `directory` (and the `tested-with` stanza of the cabal file) to use the latest Cabal, and GHC 9.2 and 9.4.  
Would you be okay with a PR?

**Comment by Rufflewind** [comment]
Feel free to, thanks!

**Comment by Kleidukos** [comment]
@Rufflewind Anything against using https://github.com/Kleidukos/get-tested/ to automatically generate the build matrix from the cabal file?
