### ISSUE TITLE
makeAbsolute ~ gives wrong path

### ISSUE THREAD

**Issue by Vic-M** [haskell/directory#150]
Running ```makeAbsolute ~/path/to/a``` gives ```/home/user/current/directory/~/path/to/a``` instead of ```/home/user/path/to/a```. Is this the intended behavior?

**Additional details**
I'm using Windows WSL2.

**Comment by Rufflewind** [comment]
Tilde expansion is a [feature of the shell](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01).

Tildes are not treated specially by `makeAbsolute`; it simply interprets them as literal tilde characters.

You might want to look for another library that offers tilde expansion.

**Comment by Vic-M** [comment]
Thanks for the reply. I'm not sure if any other libraries convert ~ but it should be simple enough to replace it using System.Directory's getHomeDirectory.
