### ISSUE TITLE
Release for GHC 9.6.1

### ISSUE THREAD

**Issue by bgamari** [haskell/directory#152]
We will need a new Hackage release for GHC 9.6.1 in the next two weeks or so. We are currently using commit 7f9066137c694ab7cef9a4ebd8c19a281fad42e4.

Thanks in advance!

**Comment by Rufflewind** [comment]
Candidate: https://hackage.haskell.org/package/directory-1.3.8.1/candidate

Draft: https://github.com/haskell/directory/releases/edit/untagged-f534974560e331f33e50

Let me know when you would like this published.

**Comment by bgamari** [comment]
Thanks @Rufflewind; the release looks great and I have bumped the GHC submodule. Release whenever you are ready.

**Comment by Rufflewind** [comment]
[Published](https://hackage.haskell.org/package/directory-1.3.8.1).
