### ISSUE TITLE
canonicalizePath regressed on Windows between directory-1.3.7.1 and directory-1.3.8.0

### ISSUE THREAD

**Issue by Bodigrim** [haskell/directory#170]
`directory-1.3.7.1` works correctly on Windows:
```
> System.Directory.canonicalizePath "\\\\localhost"
"\\\\localhost"
```
But `directory-1.3.8.0` does not:
```
> System.Directory.canonicalizePath "\\\\localhost"
"C:\\localhost"
```
I have not tracked the regression further. Might it be related to AFPP refactoring?.. CC @hasufell

**Comment by hasufell** [comment]
Yeah, just found the regression too. It was indeed introduced by my rewrite of `fromExtendedLengthPath`.

Can we communicate that this fix needs to go into the next GHC release/releases? Possibly backported.

**Comment by Rufflewind** [comment]
From https://github.com/haskell/directory/issues/170#issuecomment-1905631512:

> Can we communicate that this fix needs to go into the next GHC release/releases? Possibly backported.

@bgamari
