### ISSUE TITLE
Please revise `time` dependency to `< 1.15`

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/directory#171]
This works fine, so I guess a Hackage revision should be made to bump the `time` dependency to `< 1.15`.

* `cabal repl -z -b directory -b 'time>=1.14' --allow-newer=time`

**Comment by Rufflewind** [comment]
Resolved by https://github.com/haskell/directory/commit/f3e47598523d09b8713d921e9c69b32d71195cd1.

Also updated the Hackage metadata for directory-1.3.8.3 accordingly.
