### ISSUE TITLE
Support filepath 1.4.300.1

### ISSUE THREAD

**Issue by wz1000** [haskell/directory#174]
directory-1.3.8.3 has an upper bound excluding filepath-1.4.300.1.

This makes bumping either mutually exclusive in GHC, and we really need to bump filepath since version 1.4.200.1 is deprecated. We also would like to bump directory to fix https://github.com/haskell/directory/issues/170

A hackage revision (and a tagged git commit) should be sufficient to fix this.

**Comment by bgamari** [comment]
For the record, we will need this backported to `directory-1.3` for `ghc-9.6.5`.

**Comment by Rufflewind** [comment]
Closed by #175.

**Comment by wz1000** [comment]
Thanks @Rufflewind, can we get a tagged commit for the revision applied to directory-1.3.8.3 so that we can include it in the GHC build?

**Comment by Rufflewind** [comment]
https://hackage.haskell.org/package/directory-1.3.8.4
