### ISSUE TITLE
FR: findExecutable "" should return Nothing, like on linux

### ISSUE THREAD

**Issue by TerrorJack** [haskell/directory#180]
On Windows, `findExecutable ""` would throw `*** Exception: searchPath: invalid argument (The parameter is incorrect.)`. However, on Linux it simply returns `Nothing`. I believe this is a bug and we should align Windows behavior with Linux to also return `Nothing`.

**Comment by hasufell** [comment]
What are the affected versions?

**Comment by hasufell** [comment]
I can also reproduce this with directory-1.3.7.1 from GHC-9.4.8. So it is not related to the OsPath migration.
