### ISSUE TITLE
`directory-1.3.8.3`: relax upper bound of dependency on `base`

### ISSUE THREAD

**Issue by mpilgrem** [haskell/directory#181]
`directory-1.3.8.3` is a boot package of GHC 9.10.1 which is tied to `base-4.20.0.0`. However, the Cabal file for `directory` on Hackage specifies `base < 4.20`.

I have been tryng to build Stack with GHC 9.10.1. It compiles with `directory-1.3.8.3` if the upper bound of that package's dependency on `base` is ignored.

**Comment by hasufell** [comment]
https://github.com/haskell/directory/commit/404ddcde8a904dcf24a9348adf09a64e2ce21e49

This needs a hackage revision

**Comment by Rufflewind** [comment]
Updated https://hackage.haskell.org/package/directory-1.3.8.3/directory.cabal
