### ISSUE TITLE
Release for GHC 9.12

### ISSUE THREAD

**Issue by wz1000** [haskell/directory#191]
GHC 9.12 is currently on 6045b93c4ef7a713c8f3d6837ca69f8e96b12bf1 which is newer than v1.3.8.5 and not released in any version on hackage.

I can bump the submodule, but we need a new release on hackage with a tag to point it to.

**Comment by hasufell** [comment]
> GHC 9.12 is currently on 6045b93 which is newer than v1.3.8.5 and not released in any version on hackage.

Why is GHC on a newer commit?

**Comment by wz1000** [comment]
Because I believe the plan was to ship file-io with GHC 9.12.1.

**Comment by wz1000** [comment]
We also need #192 to be resolved.

**Comment by Rufflewind** [comment]
https://hackage.haskell.org/package/directory-1.3.9.0 has been released.
