### ISSUE TITLE
removeDirectory and symlinks

### ISSUE THREAD

**Issue by gracjan** [haskell/directory#2]
Prelude System.Directory> :!mkdir "a-directory"
    Prelude System.Directory> :!ln -s "a-directory" "a-symlink-to-a-directory"
    Prelude System.Directory> doesDirectoryExist "a-symlink-to-a-directory"
    True
    Prelude System.Directory> removeDirectory "a-symlink-to-a-directory"
    *** Exception: a-symlink-to-a-directory: removeDirectory: inappropriate type (Not a directory)

**Comment by ezyang** [comment]
Well, this behavior is at least consistent with how Python's `os.rmdir` and `os.path.isdir` operate.

**Comment by argiopetech** [comment]
This is also consistent with the way the GNU coreutils operate:

```
$ mkdir a-directory
$ ln -s a-directory a-symlink-to-a-directory
$ test -d a-directory/
$ echo $?
0
$ test -d a-symlink-to-a-directory/
$ echo $?
0
elliot@suwako /tmp/test $ rmdir a-symlink-to-a-directory
rmdir: failed to remove ‘a-symlink-to-a-directory’: Not a directory
```

Pending a compelling reason to change the behavior of `removeDirectory`, I'm going to close this issue.

**Comment by gracjan** [comment]
Agree.
