### ISSUE TITLE
removeDirectoryRecursive fails when the path root is a symbolic link

### ISSUE THREAD

**Issue by mlacorte** [haskell/directory#26]
The `removeDirectoryRecursive` documentation says, _"Symbolic links are removed without affecting their the targets."_ but the current implementation fails with an `inappropriate type (Not a directory)` exception when the root path is a symbolic link on non-Windows systems.

**Comment by Rufflewind** [comment]
That is intentional, albeit for backward compatibility reasons.  Symbolic links are considered to be files, not directories, therefore `removeDirectoryRecursive` will fail on them.  The statement you have quoted refers to symbolic links *within* the directory.

**Comment by mlacorte** [comment]
That's understandable. It'd be nice if that was made clearer in the docs, since the way it reads right now doesn't imply that the root path case is special.

**Comment by Rufflewind** [comment]
> `removeDirectoryRecursive dir` removes an existing directory *dir* together with its contents and subdirectories. Within this directory, symbolic links are removed without affecting their the targets.

Does this look better?

**Comment by mlacorte** [comment]
That seems fine. Thanks.
