### ISSUE TITLE
removeFile and directories and symlinks to directories

### ISSUE THREAD

**Issue by gracjan** [haskell/directory#3]
Prelude System.Directory> removeFile "a-symlink-to-a-directory"
Prelude System.Directory> removeFile "a-directory"
*** Exception: a-directory: removeLink: permission denied (Operation not permitted)

**Comment by ezyang** [comment]
This behavior is consistent with Python's `os.path.remove`

**Comment by Rufflewind** [comment]
It's also consistent with [`unlink`](http://pubs.opengroup.org/onlinepubs/009695399/functions/unlink.html).

**Comment by gracjan** [comment]
Agree. The recursive function is the problem in #15, not the one here.
