### ISSUE TITLE
setModificationTime gives wrong results when cross-compiling

### ISSUE THREAD

**Issue by ariep** [haskell/directory#32]
The following test program
```haskell
module Main where

import qualified System.Directory as D

main :: IO ()
main = do
  u <- D.getModificationTime "test"
  print u
  D.setModificationTime "test" u
```
compiled with directory 1.2.3.1 from github (commit 17546891), gives the expected result when compiled and run on my amd64 desktop. However, when cross-compiling and running on my raspberry pi, this gives wrong results:
```
arie@r3 ~ $ ls -l test
-rw-rw-r-- 1 arie arie 0 Aug 17 12:07 test
arie@r3 ~ $ ./setModificationTime-test 
2015-08-17 10:07:50.565253803 UTC
arie@r3 ~ $ ls -l test
-rw-rw-r-- 1 arie arie 0 Jan 10  2004 test
```
(The getModificationTime is OK: I'm at UTC+2 currently.)

The compiler is ghc-7.10.2 in both cases.

**Comment by Rufflewind** [comment]
Would you mind checking the following on your Raspberry Pi?

  - Is `utimensat` supported?  A quick way to find out is to check if `HAVE_UTIMENSAT` is defined in `include/HsDirectoryConfig.h` after running `cabal configure`.
  - What version of `unix` and `time` do you have installed?

If you can, it would help to narrow down where in this code it is failing: https://github.com/haskell/directory/blob/master/System/Directory.hs#L1275-L1313

**Comment by ariep** [comment]
> Is utimensat supported? A quick way to find out is to check if HAVE_UTIMENSAT is defined in include/HsDirectoryConfig.h after running cabal configure.

Yes, at least configure seems to think so:
```
/* Define to 1 if you have the `utimensat' function. */
#define HAVE_UTIMENSAT 1
```
Beware though that this whole cross-compiling is rather new both to me and to cabal. I'm not sure if configure knows that we're cross-compiling and knows how to do checks for the target system.

For reference, here is my cabal.config file:
```
jobs: 1
compiler: ghc
with-compiler: arm-unknown-linux-gnueabihf-ghc
with-hc-pkg: arm-unknown-linux-gnueabihf-ghc-pkg

program-locations
  ld-location:     arm-linux-gnueabihf-ld
  strip-location: arm-linux-gnueabihf-strip

program-default-options
  hsc2hs-options: -x
```

> What version of unix and time do you have installed?

time-1.5.0.1, unix-2.7.1.0

> If you can, it would help to narrow down where in this code it is failing

I added a debugging statement to the following part:
```haskell
#elif defined HAVE_UTIMENSAT
    setTime time =
      withFilePath path' $ \ path'' ->
      withArray [atime, mtime] $ \ times ->
      throwErrnoPathIfMinus1_ "" path' $
      c_utimensat c_AT_FDCWD path'' times 0
      where (atime, mtime) = swapIf isMtime (toCTimeSpec time, utimeOmit)
```
which confirmed that this part is executed, and that the `time` variable still has the right value. I tried to debug further by printing the `atime` and `mtime` variables, but these C types are not in `Show`.

**Comment by Rufflewind** [comment]
You can add Show instances easily by editing System/Directory/Internal/C_utimensat.hsc

**Comment by ariep** [comment]
OK, that gives the following:
```
time=1439912635.704517233s
atime=CTimeSpec 0 1073741822
mtime=CTimeSpec 1439912635 704517233
```
The mtime looks good. The atime is this special `utimeOmit` one:
```haskell
utimeOmit = CTimeSpec (CTime 0) (#const UTIME_OMIT)
```
Could the UTIME_OMIT constant be architecture-dependent?

**Comment by ariep** [comment]
Hm, I wrote a small C program to print the UTIME_OMIT constant on the raspberry pi, and it is also 1073741822, so that seems not to be the problem.

**Comment by ariep** [comment]
I ran the test program under strace, and the utimensat call is
```
utimensat(AT_FDCWD, "test", {{0, 0}, {1073741822, 0}}, 0) = 0
```
This is very wrong: the mtime to be set has disappeared, the atime to be set is in the place of the new mtime, and to finish it off the special value 1073741822 is somehow used as the first part (the datetime) instead of the second part (the nanoseconds). This explains the mtime date of 10 January 2004 after running the program: that is just 1073741822 interpreted as a date in unix epoch format.

I'm not sure how this can happen, looking at the Haskell code.

**Comment by Rufflewind** [comment]
It looks like the `timespec` type that got used during cross-compile is wrong and therefore incompatible with the system ABI.

Can you check `sizeof(time_t)` and `sizeof(long)` on your Raspberry Pi and *also* on the system that you used to cross-compile?

**Comment by ariep** [comment]
On the host:
```
sizeof(time_t): 8
sizeof(long): 8
```
On the raspberry pi:
```
sizeof(time_t): 4
sizeof(long): 4
```

**Comment by Rufflewind** [comment]
Yeah that makes sense now.

When you're cross-compiling, did you set the include directories to include those from the RPi SDK?

**Comment by Rufflewind** [comment]
`stat.h` found in:

```
arm-bcm2708/arm-bcm2708-linux-gnueabi/arm-bcm2708-linux-gnueabi/sysroot/usr/include/sys/stat.h
arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/arm-bcm2708hardfp-linux-gnueabi/sysroot/usr/include/sys/stat.h
arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/arm-linux-gnueabihf/libc/usr/include/arm-linux-gnueabihf/sys/stat.h
arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/libc/usr/include/arm-linux-gnueabihf/sys/stat.h
```

**Comment by ariep** [comment]
Hm, do you know where should I set those?

Per the instructions by the ku-fpg wiki page, I replaced the directory reported by  `arm-linux-gnueabihf-gcc -print-sysroot` by a symlink to a dir containing copies of the `usr` and `lib` from the rpi. Shoudn't that suffice?

**Comment by Rufflewind** [comment]
> Shoudn't that suffice?

But is GHC aware of that?  Try this:

```sh
echo >/tmp/foobar.hsc
ghc -optc=-Wp,-v /tmp/foobar.hsc
```

Look for the lines that follow `#include <...> search starts here:` and you ought to see your RPi include directories in there.

If they are present, then repeat the same procedure but invoke GHC indirectly through Cabal by running `cabal configure --ghc-options=-optc=-Wp,-v` and then rebuilding `directory`.  See if they are still there.

**Comment by ariep** [comment]
This is (part of) the output from calling the cross-compiling ghc directly as you indicate:
```
#include <...> search starts here:
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/include
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/include
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/../../../../arm-linux-gnueabihf/include  
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../arm-linux-gnueabihf/libc/usr/include/.                                     
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../arm-linux-gnueabihf/libc/usr/include/arm-linux-gnueabihf                   
End of search list.
```

For the cabal variant, I put the `ghc-options` in the `cabal.config` file instead; hope that doesn't matter.

When building "directory" through cabal, there are multiple calls to gcc, apparently. This is the first one, before cabal's "Resolving dependencies..." message:
```
#include <...> search starts here:
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/base_2NsNayXyUzV1JH6WpNbER4/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/include
/home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/include
/home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/../../../../arm-linux-gnueabihf/include
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../arm-linux-gnueabihf/libc/usr/include/.
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../arm-linux-gnueabihf/libc/usr/include/arm-linux-gnueabihf
End of search list.
```
Then another one, after the "Configuring directory-1.2.3.1..." message, but before the configure output. The search list is exactly equal to the one above.

Then a final one, after ghc's "[5 of 5] Compiling System.Directory", but before "In-place registering directory-1.2.3.1...". This one is different:
```
#include <...> search starts here:
 dist/dist-sandbox-956d6198/build/autogen
 dist/dist-sandbox-956d6198/build
 include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/unix_CYrkiOGRXtGIJ0UuvHyl1i/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/bytes_3ta8QVxlpYNKR7sUcHtpIE/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/time_ErRVsvxYNjQCqZ4JF6dZON/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/base_2NsNayXyUzV1JH6WpNbER4/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/include
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/include
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/../../../../arm-linux-gnueabihf/include
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../arm-linux-gnueabihf/libc/usr/include/.
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../arm-linux-gnueabihf/libc/usr/include/arm-linux-gnueabihf
End of search list.
```

This seems OK, no? `sys/stat.h` is present in the last line of each of these search lists.

**Comment by Rufflewind** [comment]
First check hsc2hs (the cross-compiled version):

```sh
cat >bar.hsc <<EOF
#include <sys/stat.h>
x = #{const sizeof(time_t)}
EOF
hsc2hs --cflag=-Wp,-v bar.hsc
cat bar.hs
```

The correct result should be `x = 4` since `time_t` should be a 32-bit integer.  If this is correct, repeat the same thing but do it via Cabal:

```sh
cabal clean
cabal configure --hsc2hs-option=--cflag=-Wp,-v
echo 'x = #{const sizeof(time_t)}' >>System/Directory/Internal.hsc
cabal build
tail dist/build/System/Directory/Internal.hs
```

**Comment by ariep** [comment]
> First check hsc2hs (the cross-compiled version):

Wait, I'm confused. Where and how should I run it?

The cross-compiled version cannot be run on the host, because the executable is made for the target architecture.

It also cannot be run on the target, at least not directly: the executable arm-unknown-linux-gnueabihf-hsc2hs is in fact a shell script, which refers not only to the actual executable, but also to some files (among which a template file "template-hsc.h") that are not present on the target. Should I copy these files to the target and try to set things up so that the script will run?

Note that I never told cabal to use the cross-compiled hsc2hs (unlike ghc, ghc-pkg, ld and strip): it was not mentioned at all in the ku-fpg wiki. This also seemed logical, because hsc2hs is run on the host, so you don't want a cross-compiled version.

Maybe the hsc2hs from the host (this is the plain one from the bootstrapping ghc used to build the cross-compiling ghc), which is used right now when cross-compiling, is not passed the right include directories?

**Comment by Rufflewind** [comment]
> Wait, I'm confused. Where and how should I run it?

The one that comes with the ghc that you use for cross-compilation, which should also be the one that Cabal invokes in your cross-compilation configuration.  I don't know if there's any actual difference between the two … if there is any it probably just sets up the default C compiler and flags; if there isn't then the flags would need to be passed explicitly (including a `--cross-compile` flag for hsc2hs).

On second thought, just forget about the first section about invoking `hsc2hs` directly since I'm not really sure what are the appropriate flags for it yet.  Instead, just run it indirectly via Cabal since that's the one we need to investigate.

> Maybe the hsc2hs from the host (this is the plain one from the bootstrapping ghc used to build the cross-compiling ghc), which is used right now when cross-compiling, is not passed the right include directories?

That is what we are trying to find out here.

**Comment by ariep** [comment]
> On second thought, just ignore the first section about invoking hsc2hs directly since I'm not really sure what are the appropriate flags for it yet. Instead, just run it indirectly via Cabal since that's the one we need to investigate. Do it with --verbose so we can see what Cabal is doing.

OK, I have done so. It gives `x = 8`, which as you say is wrong, so we're on the right track.

Here is some output from `cabal build --verbose`.

```
Preprocessing library directory-1.2.3.1...
creating dist/build/System/Directory
creating dist/build/System
creating dist/build/System/Directory
/usr/bin/hsc2hs '--cc=/usr/bin/gcc' '--ld=/usr/bin/gcc' '--cflag=-D__GLASGOW_HASKELL__=710' '--cflag=-Dlinux_BUILD_OS=1' '--cflag=-Dx86_64_BUILD_ARCH=1' '--cflag=-Dlinux_HOST_OS=1' '--cflag=-Darm_HOST_ARCH=1' '--cflag=-Iinclude' '--cflag=-Idist/build/autogen' '--cflag=-include' '--cflag=dist/build/autogen/cabal_macros.h' '--cflag=-I/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/unix_CYrkiOGRXtGIJ0UuvHyl1i/include' '--cflag=-I/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/time_ErRVsvxYNjQCqZ4JF6dZON/include' '--cflag=-I/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/bytes_3ta8QVxlpYNKR7sUcHtpIE/include' '--cflag=-I/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/base_2NsNayXyUzV1JH6WpNbER4/include' '--cflag=-I/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/include' '--lflag=-L/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/unix_CYrkiOGRXtGIJ0UuvHyl1i' '--lflag=-Wl,-R,/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/unix_CYrkiOGRXtGIJ0UuvHyl1i' '--lflag=-lrt' '--lflag=-lutil' '--lflag=-ldl' '--lflag=-lpthread' '--lflag=-L/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/time_ErRVsvxYNjQCqZ4JF6dZON' '--lflag=-Wl,-R,/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/time_ErRVsvxYNjQCqZ4JF6dZON' '--lflag=-L/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/filep_29pyVwnUyBE6kEyIhifz2P' '--lflag=-Wl,-R,/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/filep_29pyVwnUyBE6kEyIhifz2P' '--lflag=-L/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/bytes_3ta8QVxlpYNKR7sUcHtpIE' '--lflag=-Wl,-R,/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/bytes_3ta8QVxlpYNKR7sUcHtpIE' '--lflag=-L/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/deeps_2I70b8M8s5p23eitWtXIeR' '--lflag=-Wl,-R,/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/deeps_2I70b8M8s5p23eitWtXIeR' '--lflag=-L/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/array_HnDHE6WOgoj97o9lI9ovvx' '--lflag=-Wl,-R,/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/array_HnDHE6WOgoj97o9lI9ovvx' '--lflag=-L/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/base_2NsNayXyUzV1JH6WpNbER4' '--lflag=-Wl,-R,/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/base_2NsNayXyUzV1JH6WpNbER4' '--lflag=-L/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/integ_DrKBJ7wo9zkGiLmhPp116e' '--lflag=-Wl,-R,/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/integ_DrKBJ7wo9zkGiLmhPp116e' '--lflag=-L/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/ghcpr_8TmvWUcS1U1IKHT0levwg3' '--lflag=-Wl,-R,/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/ghcpr_8TmvWUcS1U1IKHT0levwg3' '--lflag=-L/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/rts' '--lflag=-Wl,-R,/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/rts' '--lflag=-lm' '--lflag=-lrt' '--lflag=-ldl' -o dist/build/System/Directory/Internal.hs System/Directory/Internal.hsc -x '--cflag=-Wp,-v'
ignoring nonexistent directory "/usr/local/include"
ignoring nonexistent directory "/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/../../../../x86_64-pc-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 include
 dist/build/autogen
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/unix_CYrkiOGRXtGIJ0UuvHyl1i/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/time_ErRVsvxYNjQCqZ4JF6dZON/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/bytes_3ta8QVxlpYNKR7sUcHtpIE/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/base_2NsNayXyUzV1JH6WpNbER4/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/include
 /usr/lib64/ghc-7.10.2/include/
 /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include
 /usr/lib/gcc/x86_64-pc-linux-gnu/4.8.4/include-fixed
 /usr/include
End of search list.
```
Indeed, this last search list seems wrong: it refers to the host system's `/usr/include` etc, not to the copy of the raspberry pi's include files. The directory `/usr/include` is not passed to hsc2hs by cabal; I guess it is built-in somehow?

I'll see if I can add some extra `-I` options to cabal's invocation of hsc2hs to fix this.

**Comment by ariep** [comment]
Hm, I went ahead and added the following to cabal's hsc2hs-options:
```
--cflag=-nostdinc
-I/home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/include
-I/home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../arm-linux-gnueabihf/libc/usr/include/arm-linux-gnueabihf
-I/home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/include
-I/home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed
-I/home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/../../../../arm-linux-gnueabihf/include
-I/home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../arm-linux-gnueabihf/libc/usr/include/.
```
With these flags, the search path becomes
```
#include <...> search starts here:
 include
 dist/build/autogen
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/unix_CYrkiOGRXtGIJ0UuvHyl1i/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/time_ErRVsvxYNjQCqZ4JF6dZON/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/bytes_3ta8QVxlpYNKR7sUcHtpIE/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/base_2NsNayXyUzV1JH6WpNbER4/include
 /home/arie/programs/rpi-cross/local/lib/arm-unknown-linux-gnueabihf-ghc-7.10.2/include
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../arm-linux-gnueabihf/libc/usr/include/arm-linux-gnueabihf
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/include
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../lib/gcc/arm-linux-gnueabihf/4.8.3/../../../../arm-linux-gnueabihf/include
 /home/arie/programs/rpi-cross/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/../arm-linux-gnueabihf/libc/usr/include/.
 /usr/lib64/ghc-7.10.2/include/
End of search list.
```
which looks a lot better, I guess. Only the last line, which refers to the host's ghc's include dir, looks off. But that should be overriden by the cross-compiler's include dir, which is on an earlier line.

However, this does not change the 8 into a 4...

Could there be some caching mechanism that is not flushed by `cabal clean`? The `cabal configure` output says
```
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
```
Do you know how these are cached? Could this affect which `<sys/stat.h>` is later included?

**Comment by Rufflewind** [comment]
This line is problematic:

```sh
/usr/bin/hsc2hs
    '--cc=/usr/bin/gcc'
    '--ld=/usr/bin/gcc'
    …
    -o dist/build/System/Directory/Internal.hs
    System/Directory/Internal.hsc
    -x # equivalent to --cross-compile
    '--cflag=-Wp,-v'
```

As you can see, it's using your *system* `gcc`, and as a consequence the include directories (as you noted) are wrong.

Cabal is kind of out of the loop: it doesn't know you are cross-compiling, so it's just using your system C compiler.  It seems the [only way to do this right now](https://stackoverflow.com/a/2547347) is via:

```sh
cabal configure --with-gcc=/path/to/cc --with-ld=/path/to/ld …
```

While you're at it, you probably also want to [make sure the autoconf script (`./configure`) receives the correct flags](http://stackoverflow.com/a/15235752):

```sh
cabal configure --configure-option=--host=arm-linux-gnuabihf …
```

Make sure you see this in the output:

    checking for arm-linux-gnueabihf-gcc... arm-linux-gnueabihf-gcc

If you see `no`, then it probably means you need to add the compilers to your `PATH`.

**Comment by Rufflewind** [comment]
> Could there be some caching mechanism that is not flushed by `cabal clean`? The `cabal configure` output says
>
>     checking for sys/types.h... (cached) yes
>     checking for sys/stat.h... (cached) yes

Autoconf has [caching](http://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Caching-Results.html) and can store them in [cache files](http://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Cache-Files.html#Cache-Files), but cache files are disabled by default.  What you see here is actually the result of checking the same header multiple times in one run (notice there are two repeated instances of `checking for sys/types.h...` and `checking for sys/stat.h...`.

**Comment by ariep** [comment]
It works now!

For reference, this is the working cabal.config:
```
jobs: 1

compiler: ghc
with-compiler: arm-unknown-linux-gnueabihf-ghc
with-hc-pkg: arm-unknown-linux-gnueabihf-ghc-pkg
configure-option: --host=arm-linux-gnueabihf

program-locations
  gcc-location:   arm-linux-gnueabihf-gcc
  ld-location:    arm-linux-gnueabihf-ld
  strip-location: arm-linux-gnueabihf-strip

program-default-options
  hsc2hs-options: -x
```
Both the directory with the cross-compiling ghc and the one with the special gcc, ld and strip need to be in your path.

Many, many thanks for your help.
