### ISSUE TITLE
getModificationTime on Windows should give a better error message

### ISSUE THREAD

**Issue by ndmitchell** [haskell/directory#38]
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
    Prelude> import System.Directory
    Prelude> readFile "foo"
    *** Exception: foo: openFile: does not exist (No such file or directory)
    Prelude System.Directory> getModificationTime "foo"
    *** Exception: getFileAttributesExStandard: does not exist (The system cannot find the file specified.)

Error message should mention the file you are trying to use.

**Comment by Rufflewind** [comment]
This was fixed in [1.2.3.0](https://github.com/haskell/directory/commit/5f431e0905acb7e5d1c02beea0eefad94829645e), though I forgot to mention it in the changelogs.

GHC 7.10.2 comes with 1.2.2.0 IIRC.

**Comment by ndmitchell** [comment]
Awesome!
