### ISSUE TITLE
getCurrentDirectory should raise better error string when cwd doesn't exist

### ISSUE THREAD

**Issue by thomie** [haskell/directory#39]
@ezyang reports in https://ghc.haskell.org/trac/ghc/ticket/11280:

Run this script in a directory which no longer exists:

```
import System.Directory
main = getCurrentDirectory >>= putStrLn
```

Currently the error looks like:

```
ezyang@sabre:~/test$ ./test
bash: ./test: No such file or directory
```

It would be nicer to give a better message in this case.

Originally reported: ​https://github.com/haskell/cabal/issues/2902

**Comment by ezyang** [comment]
OK, this is not actually a bug with directory, and also there's been a commit which improves it in any case.
