### ISSUE TITLE
copyFile does not copy metadata

### ISSUE THREAD

**Issue by thomie** [haskell/directory#40]
In https://ghc.haskell.org/trac/ghc/ticket/5251, GHC trac user Orphi reports:

The `copyFile` function fails to copy various metadata to do with a file.

(GHC 7.0.2, directory 1.1.0.0 - not that I expect it to matter.)

The cause is simple: Rather than calling an OS-specific "please copy this file" function, the directory package attempts to implement this logic itself. And does it completely wrong.

The fix should be easy; we just need somebody to figure out what the appropriate native OS function is on each platform.

**Comment by thomie** [comment]
Comment by Orphi:

For reference, here are the Windows-specific things which are not copied by `copyFile`:

The "hidden" attribute.
The "system" attribute.
The "compressed" attribute.
The "indexed" attribute.
Security settings.
File owner.
Auditing settings.
Alternative Data Streams.
The "archive" bit is also not copied - but this is almost certainly the correct thing to do.

Interestingly, the "read only" attribute is copied correctly.

I was unable to test the following, but I believe they will be lost too:

Sparse files [will become dense when copied].
FS-level encryption.
As you can see, Windows stores a hell of a lot of metadata about files, almost all of which the naive copyFile implementation is blindly stripping off. It wouldn't surprise me if it drops metadata on Unix too, although I haven't had time to test yet.

**Comment by Rufflewind** [comment]
Windows has `CopyFile[Ex]`, which does copy metadata.

There is no such equivalent on Unix-like systems.  The `cp` utility does have a`-p` flag that preserves mode, ownership, and timestamps, but all of this is [done manually](http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/cp.c?id=5171befcb122b12677f60715603be091625a9e08#n315).

I'm not sure it's good idea to change what `copyFile` does now – it would break backward compatibility in a rather subtle way.  It may be better to add a new function that copies the file contents as well as metadata.
