### ISSUE TITLE
canonicalizePath "." has changed behaviour

### ISSUE THREAD

**Issue by ndmitchell** [haskell/directory#42]
The the version of directory that ships with GHC 8.0 RC2 I see `canonicalizePath "." == "C:\\Neil\\"`. On GHC 7.10 it's `"C:\\Neil"` without the trailing slash. This change of behaviour has broken the Shake test suite, and is not documented in the changelog. If it's an intentional change, it should be in the changelog. If it's unintentional, you still have a small window to revert it.

CC @hvr, who seems to be doing GHC 8.0 release management things.

**Comment by hvr** [comment]
/cc'ing also @bgamari whom I help with rls mgmt, but who is ultimately the one in charge and spending his weekends with GHC 8 release managament... :-)

**Comment by hvr** [comment]
@ndmitchell just to clarify, the semantic change you're complaining occured in the hackage-released v1.2.5 release, and would therefore constitute a PVP violation?

**Comment by ndmitchell** [comment]
@hvr - I tried 7.10 which seems to have 1.2.2.0 and it doesn't include the trailing slash. I tried 1.2.5.0 and it does. I'm not really complaining about PVP violations, more undocumented change that might or might not have been intentional. For info, I've fixed this in Shake with 9f6f901ac08b6615e67b97d79b5d6492b809a72d.

**Comment by Rufflewind** [comment]
The change occurred in 1.2.3.0.  It was not intentional.

The new implementation of `canonicalizePath` makes use of `makeAbsolute`, which uses `normalise` to clean up the path.  Hence, this is a manifestation of [how `normalise` currently works](https://github.com/haskell/filepath/issues/12).

I'm not sure what's the "right" behavior for this, so I'll just revert to the old behavior.

(This change will also affect `makeAbsolute`.)

**Comment by ndmitchell** [comment]
Specifically, what are you passing into `normalise`? And does `normalise` do anything other than make the drive upper case on Windows? If not, I'd be tempted to implement that as a Windows-only single tweak, rather than use `normalise`, which is a big hammer which is a little dodgy at the best of times.

**Comment by Rufflewind** [comment]
It looks roughly like this:

~~~hs
makeAbsolute path = normalise . (</> path) <$> getCurrentDirectory

canonicalizePath path = normalise <$> (transform =<< makeAbsolute path)
  where transform = {- platform-specific function -}
~~~

Besides uppercasing the drive letter, `normalise` also removes redundant dots and slashes, and changes to the correct type of slash (Windows-only).
