### ISSUE TITLE
directory-1.2.6.1 fails to install

### ISSUE THREAD

**Issue by kolmodin** [haskell/directory#49]
```
Failed to install directory-1.2.6.1
Last 10 lines of the build log ( /home/travis/build/kolmodin/binary/.cabal-sandbox/logs/directory-1.2.6.1.log ):
[1 of 1] Compiling Main             ( /tmp/directory-1.2.6.1-2587/directory-1.2.6.1/dist/dist-sandbox-29f73198/setup/setup.hs, /tmp/directory-1.2.6.1-2587/directory-1.2.6.1/dist/dist-sandbox-29f73198/setup/Main.o )
Linking /tmp/directory-1.2.6.1-2587/directory-1.2.6.1/dist/dist-sandbox-29f73198/setup/setup ...
Configuring directory-1.2.6.1...
Warning: The 'build-type' is 'Configure' but there is no 'configure' script.
setup: configure script not found.
```

Looks like `build-type: Configure` but there is no `configure` file included in the package.

**Comment by kolmodin** [comment]
```
$ cabal --version
cabal-install version 1.18.0.4
using version 1.18.1.3 of the Cabal library 
```

**Comment by hvr** [comment]
That's annoying... :-(

we'll have to blacklist `directory-1.2.6.1` on Hackage

@bgamari we shouldn't ship GHC 8.0 with a package version that isn't reinstallable from Hackage, so we'll want a `directory-1.2.6.2` for GHC 8.0!

@Rufflewind can you provide us with a `directory-1.2.6.2` soon (i.e. before end of week)

@dcoutts we should add a validation to hackage-server to reject tarballs which state build-type configure but lack an executable `configure` script

**Comment by Rufflewind** [comment]
> Looks like `build-type: Configure` but there is no `configure` file included in the package.

Sorry, looks like I forgot to generate the `configure` script when I uploaded the package.

I can't edit packages that have already been uploaded, so I've uploaded a [new version](https://hackage.haskell.org/package/directory).

I'll add a check in my Hackage uploader to make sure `configure` is present in the tarball before uploading.

**Comment by hvr** [comment]
@Rufflewind I've also noticed the source-tarball contains files that doesn't belong in there; `cabal sdist` is supposed to be idempotent if you re-sdist. Your tarball fails that property

**Comment by hvr** [comment]
GHC HEAD updated to use v1.2.6.2 https://github.com/ghc/ghc/commit/8556f56b71f979f70f503e1d23a822b21947f7ab

@bgamari plz merge (& validate) to 8.0 at your convenience

**Comment by Rufflewind** [comment]
> I've also noticed the source-tarball (`directory-1.2.6.1`) contains files that don't belong in there

Looks like I accidentally uploaded the tarball generated by GitHub instead of the one generated by `cabal sdist`… /facepalm

**Comment by hvr** [comment]
Fyi, I edited in a `base<0` constraint at http://hackage.haskell.org/package/directory-1.2.6.1/revisions/, so now you can't even `cabal install directory-1.2.6.1` without the solver complaining.

**Comment by Rufflewind** [comment]
> Fyi, I edited in a `base<0` constraint at http://hackage.haskell.org/package/directory-1.2.6.1/revisions/, so now you can't even `cabal install directory-1.2.6.1` without the solver complaining.

Heh, thanks.  That's a neat hack :P

**Comment by kolmodin** [comment]
Looks like there are no more action items in this bug;

 - `directory-1.2.6.2` has been released with a fix, and merged into GHC.
 - `directory-1.2.6.1` has been blacklisted.
 - I filed haskell/hackage-server#490 to prevent this from happening again.
