### ISSUE TITLE
remove cbits/directory.c file

### ISSUE THREAD

**Issue by hvr** [haskell/directory#50]
or more generally rethink how to handle the cbits in future, they seem kinda redundant by now

this includes figuring out if there's anyone depending on the `.h` files that may break...

**Comment by Rufflewind** [comment]
I [posted about this in the past](https://mail.haskell.org/pipermail/libraries/2015-June/025757.html) but got no responses or complaints.

I think they can be replaced with hsc2hs.

Would removing them require bumping the major version?

**Comment by hvr** [comment]
IMHO even hsc2hs is overkill here, just plain CapiFFI would probably suffice

**Comment by Rufflewind** [comment]
> IMHO even hsc2hs is overkill here, just plain CapiFFI would probably suffice

Wouldn't that require dropping support for GHC 7.4?

**Comment by hvr** [comment]
> Wouldn't that require dropping support for GHC 7.4?

No. Evidence: `unix` makes extensive use of `CapiFFI` and works with GHC 7.4 :-)

See also https://ghc.haskell.org/trac/ghc/wiki/LanguagePragmaHistory

**Comment by Rufflewind** [comment]
Oh oops, I saw it in the release notes for 7.6 and thought it was introduced then.

**Comment by hvr** [comment]
@Rufflewind yeah, that's been a cause of common confusion. There's quite a few who came to believe that CapiFFI excludes GHC 7.4

**Comment by Rufflewind** [comment]
Based on a few Google searches, I don't think anyone uses the header or any of its functions, so I'll remove them and bump only the minor version.

(I also forgot that I had already removed the dependence on the C bits in the library code, so all I have to do now is to actually delete them.)
