### ISSUE TITLE
RenameDirectory: hPutChar, invalid character (Unicode issue Windows)

### ISSUE THREAD

**Issue by YellowOnion** [haskell/directory#51]
Title says it all.

**Comment by Rufflewind** [comment]
Is your [console codepage](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682064.aspx) set to one of the Unicode ones (e.g. 65001 ≡ UTF-8)?

**Comment by YellowOnion** [comment]
that code page isn't listed, according to [this](https://hackage.haskell.org/package/base-4.8.2.0/docs/System-IO.html#g:23) "on Windows, we currently do not support double-byte encodings"

So perhaps it's an upstream issue, but I'm confused as to how I got the file names out of the file system in the first place then.

The irony of this entire thing is that I'm trying to rename Unicode file names so they will play nice with nginx on windows, which seems to be having a similar issue.

**Comment by Rufflewind** [comment]
It is necessary to set the console codepage to one that supports Unicode, otherwise the GHC runtime is not able to display non-ASCII characters in Command Prompt.

You can do this using `chcp` in Command Prompt, or use the [Win32 API](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682064.aspx).

**Comment by YellowOnion** [comment]
Well the thing is, that I'm not trying to print the characters, I'm trying to rename Directories (as the function name implies), but I get this error when trying to pass unicode strings (that I had already got from listDirectory).

**Comment by Rufflewind** [comment]
Please post the steps needed to reproduce this problem. I was not able to reproduce this problem unless the `renameDirectory` fails, in which case GHC attempts to print an error message containing the filename and thus fails.

**Comment by YellowOnion** [comment]
Strange, now that I have changed the code page, and re written out my code in to ghci, I get no error.

```` haskell
files <- getCurrentDirectory >>= getDirectoryContents
let filesFrom = filter (any (== '\65306')) files
let filesTo = map (map (\a -> if a == '\65306' then '_' else a)) filesFrom
forM_ (zip filesFrom filesTo) (uncurry renameDirectory)
````

Thanks for the chcp command, I didn't realise it was possible to change to utf8 in cmd.exe, maybe that'll help with other issues I have. (I've tried msys2 + bash, but ghci doesn't like that either).

**Comment by Rufflewind** [comment]
Still having problems with issue?

**Comment by YellowOnion** [comment]
Nope, It was just a one time script, I wouldn't know how to proceed in reproducing.
