### ISSUE TITLE
Not in scope: `<*>'

### ISSUE THREAD

**Issue by Heather** [haskell/directory#53]
directory-1.2.6.2

System\Directory.hs:1449:11:
    Not in scope: `<*>'

>ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3

https://github.com/haskell/directory/commit/62ff034a2a80d9ebb89801afea2321be68362420#diff-a25d2dbcd01120819dff319c67ff3fecR1314

**Comment by hvr** [comment]
For the record, this affects only `os(windows)`

**Comment by Heather** [comment]
@hvr very much possibly but it's a blocking bug

**Comment by Rufflewind** [comment]
Would you mind checking if ba689623323720f0ee1f8d0dbcf7c5499e8c3e06 works?

**Comment by Heather** [comment]
@Rufflewind ahm... autotools on windows is complicated

**Comment by Rufflewind** [comment]
Here's one with the configure script pre-generated: [directory-1.2.6.3.tar.gz](https://github.com/haskell/directory/files/243773/directory-1.2.6.3.tar.gz)

**Comment by Heather** [comment]
@Rufflewind good, installs fine `Installed directory-1.2.6.3`

**Comment by Rufflewind** [comment]
Thanks for testing!
