### ISSUE TITLE
Configuring AppVeyor CI

### ISSUE THREAD

**Issue by Rufflewind** [haskell/directory#54]
@hvr Would you mind configuring this for https://github.com/haskell/directory?  I have an AppVeyor project set up already for haskell/directory, but building commits is not automatic since I can't add webhooks to the project.  Thanks!

**Comment by hvr** [comment]
I hope this works: https://ci.appveyor.com/project/hvr/directory

**Comment by Rufflewind** [comment]
Looks good, thanks a bunch :)
