### ISSUE TITLE
copyFileWithMetadata doesn't preserve timestamps on Windows

### ISSUE THREAD

**Issue by jacereda** [haskell/directory#56]
I'd be interested in a `copyFile` operation that preserves timestamps. Any reason for `copyFileWithMetadata` behaviour to be different across platforms regarding timestamps?

Any of these seems fine:

- remove the timestamps copy under Posix for `copyFileWithTimestamps` and add a new `copyFileWithTimestamps`
- make `copyFileWithMetadata` copy timestamps as well under Windows.

**Comment by Rufflewind** [comment]
Which "timestamp" are you referring to?

**Comment by jacereda** [comment]
I need modification, but wouldn't mind if access time was also copied.

**Comment by Rufflewind** [comment]
Modification time should be copied on all platforms, including Windows.  Mind showing the steps to reproduce the problem?

**Comment by jacereda** [comment]
You're right. I just checked and the mtime is copied. I'm adjusting a build system and I was getting unnecessary rebuilds when doing `copyFileWithMetadata` vs doing a `copyFile` when both files differ. Sorry for the noise, looks like the problem is somewhere else.
