### ISSUE TITLE
add rename function without directory/file distinction 

### ISSUE THREAD

**Issue by agentm** [haskell/directory#58]
On both Windows and Posix platforms, the invocation of the underlying rename function is identical, so the value of explicitly choosing either the directory or file API is diminished. In my specific use case, I wanted to implement [renameSync](https://github.com/agentm/project-m36/blob/master/ProjectM36/Persist.hs#L36-L48) but had to swipe the System.Directory's implementation instead of being able to rely on the System.Directory module.

In addition, checking for a file or directory in advance opens a potential race condition and blocks usage of rename against non-file, non-directory nodes such as devices.

For my use case, a rename function which ignores the directory/file distinction would have solved the problem.

**Comment by Rufflewind** [comment]
Like this? https://github.com/Rufflewind/directory/commit/de6a440288d85d4804aceecf8b73344d9a59555d

**Comment by agentm** [comment]
Thanks! That's spot on.
