### ISSUE TITLE
removeDirectoryRecursive can throw an exception if a file vanishes before it removes it

### ISSUE THREAD

**Issue by joeyh** [haskell/directory#60]
```
> removeDirectoryRecursive "/tmp/d"
Exception: /tmp/d/zzzzz: removeDirectoryRecursive: does not exist (No such file or directory)
```

Here /tmp/d/ contained a directory foo (with many subdirectories so it took some time to delete), and a subsequent file zzzzzz. Immediately after pressing enter in ghci, I launched a rm zzzzzz. So getDirectoryContents included the file, but it was gone by the time removeFile ran.

I feel that this is a surprising failure mode, and one that would be very easy to recover from, making uses of removeDirectoryRecursive more robust. If removeFile throws an exception due to the file no longer existing, removeDirectoryRecursive could continue with removing the rest of the directory and not propagate the exception.

(Testing rm -rf (on linux) in similar circumstances, I found that it skips over files that have already been deleted by something else, rather than failing.)

**Comment by Rufflewind** [comment]
See if this fixes your issue: https://github.com/Rufflewind/directory/commit/baba66c0659f99889440f2879c04eff789e5aa2f

**Comment by Rufflewind** [comment]
This should be fixed by https://github.com/haskell/directory/commit/1a5edff2b6fc1620bab7ec3ebe9c0aa49a76fbc8

Feel free to re-open the issue if you still encounter problems.  Thanks for the bug report!
