### ISSUE TITLE
recently added getFileSize conflicts with System.Posix.Files

### ISSUE THREAD

**Issue by joeyh** [haskell/directory#66]
Same kind of problem as #52, so see discussion there.

**Comment by Rufflewind** [comment]
I don't see `getFileSize` in [System.Posix.Files](https://hackage.haskell.org/package/unix-2.7.2.1/docs/System-Posix-Files.html)?

**Comment by joeyh** [comment]
Phil Ruffwind wrote:
> I don't see getFileSize in System.Posix.Files?

Sorry, it's in System.PosixCompat.Files .. and that implementation is
buggy (https://github.com/jystic/unix-compat/issues/16)

This issue can probably be closed.

-- 
see shy jo
