### ISSUE TITLE
findExecutablesInDirectories can return directories

### ISSUE THREAD

**Issue by harendra-kumar** [haskell/directory#71]
`findExecutablesInDirectories` [does not check](https://github.com/haskell/directory/blob/af307f52ca94ed232d1372fc6760a4b3efa243c7/System/Directory.hs#L1181) whether we found a file or a directory. Is that intended or a bug? Doesn't `executable` mean `executable files` as in the case of `findExecutable`?

**Comment by harendra-kumar** [comment]
Ah, never mind, got confused. `findFileWithIn` does it.

**Comment by Rufflewind** [comment]
I don't believe directories can ever be `executable` in this library. Instead they would be considered `searchable`.

**Comment by harendra-kumar** [comment]
true!
