### ISSUE TITLE
listDirectoryRecursive?

### ISSUE THREAD

**Issue by fisx** [haskell/directory#73]
Is there anything that makes this hard to do right?  Would you accept a PR?

thanks-

**Comment by Rufflewind** [comment]
Any recursive file system operation needs to be cautious of symbolic links. Other than that I can't think of anything else that might be tricky (it helps that it doesn't modify the file system). removeDirectoryRecursive should give you an idea.

A PR would be welcome.

**Comment by fisx** [comment]
Ah, I just found http://hackage.haskell.org/package/directory-tree.  (-:

I still think it's a good addition to this package.  I'll try to make the time soon.  Thanks for the quick feedback!

**Comment by pranaysashank** [comment]
I'd like to submit a PR for this and I got a question.
Should the `listDirectoryRecursive` function signature should be
 `FilePath -> IO [(FilePath, [FilePath])]`, so that it lists each subdirectory with its corresponding contents?

**Comment by fisx** [comment]
You probably want this:

```haskell
import Data.Tree
listDirectoryRecursive :: FilePath -> Forest FilePath
```

so that the children of the input argument will form the output tree list.

I like this because it will take the least effort from traversing the directory tree to constructing the path tree.  Then if you need the output in another form, you can easily get it with a pure function.

**Comment by Rufflewind** [comment]
Since `directory` is a boot library, it would be best to avoid incurring a dependency on `containers`.  Perhaps define a specialized tree type for this?

**Comment by fisx** [comment]
Oops, sorry, good point.

In that case I think it's best to pay the extra price for getting complete (relative) paths for all tree nodes, like this:

```
["sub", "sub/file", "sub/sub2", "sub/sub2/deep", "file", ...]
```

the extra cost for constructing the longer output (in bytes) should be negligible in the face of the cost for I/O.

**Comment by chris-martin** [comment]
It seems like there's some conflict of interest between 

* `directory` being a boot library, thus needing to be conservative in its API and dependencies, and
* `directory` being a library that users encounter very early on when learning Haskell and really want more functionality out of.

Perhaps it would be best to have this sort of non-core feature in a separate "kitchen sink" directory library (`directory-extras`?) that the `directory` library's documentation could officially recommend. Are there any candidate libraries already out there?

**Comment by lehins** [comment]
There is a function [sourceDirectoryDeep](https://www.stackage.org/haddock/lts-10/conduit-extra/Data-Conduit-Filesystem.html#v:sourceDirectoryDeep) in [conduit-extra](https://www.stackage.org/package/conduit-extra) that take care of the streaming directory contents recursively, with an option to handle symlinks differently and most importantly it does all that in constant memory.

**Comment by Rufflewind** [comment]
I think @chris-martin has a very good point here.  This is probably better (and easier) done in a more high-level library, whereas `directory` should focus on providing a platform-independent primitives.

I am closing this issue.  Feel free to add any other suggestions for high-level libraries to this thread for others to see.  If you believe `directory` is missing some kind of primitive needed to implement `listDirectoryRecursive`, please open a new issue.

Thanks everyone for the discussion here!
