### ISSUE TITLE
canonicalizePath doesn't respect directory substitutions on Windows

### ISSUE THREAD

**Issue by varosi** [haskell/directory#76]
Related to https://github.com/mrkkrp/path-io/issues/30

If we use substituted paths (using *subst* shell command) we may create a new Windows drive for specific paths on other drives. This is called "directory substitution". It's used often in production environments. As we use it on Jenkins building farm. We try to overcome Windows max. path length issue with substituting long paths into smaller on a substituted drive. 
Here is an example of P:

> D:\......\> subst P: .
> P:\>stack repl --package directory-1.3.1.4
> ...
> Prelude> import System.Directory
> Prelude> canonicalizePath "."
> "D:\\Work\\long\\builder\\jenkins\\home\\workspace\\work_master-IH6I4ZJQUG22JDFTMS624VMTMO5APB7UUFMDD7ZRLLQLR32Y2H5A\\work"

This is not correct and it should return the path in the correct drive, like:

> "P:\\work"

**Comment by varosi** [comment]
Some additional information on the problem:
http://pdh11.blogspot.bg/2009/05/pathcanonicalize-versus-what-it-says-on.html

**Comment by varosi** [comment]
I have added some comments in mrkkrp/path-io#30 and I think that Stack should use *absolute* and not *canonical* paths for directory operations.

**Comment by Rufflewind** [comment]
`canonicalizePath` is intended to remove as many indirections as possible.  I'm not sure making `canonicalizePath` produce a *less canonical* path is a desirable goal here – it seems to run counter to its stated purpose.

Internally, this is a consequence of `GetFinalPathNameByHandle`, which offers a pretty accurate way to retrieve the original path of any file object.  This can eliminate many kinds of indirections, including ones I didn't even know existed like `subst`!

**Comment by varosi** [comment]
Yes, you're sure. Our problem should be resolved on higher level with possibly using different functions from *directory*.
