### ISSUE TITLE
Add support for XDG_CONFIG_DIRS

### ISSUE THREAD

**Issue by ocharles** [haskell/directory#78]
https://github.com/Rufflewind/directory/commit/ab9d0810ce0172e10ff1ca437ad7f723d6648f0d gave us support for XDG, but it doesn't add support for `XDG_CONFIG_DIRS`. This environment variable is directly part of the spec, as mentioned in https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by Rufflewind** [comment]
I wonder what the semantics for Windows should be?  The closest I can think of is `CommonApplicationData`.

**Comment by ocharles** [comment]
Awesome, thank you!
