### ISSUE TITLE
Use SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE for symlinking on Windows

### ISSUE THREAD

**Issue by YellPika** [haskell/directory#83]
Windows 10 added support for creating symbolic links without administrator privileges when the system is in developer mode, but `CreateSymbolicLink` will still fail unless `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` is passed as a flag.

`directory` doesn't seem to expose this functionality. Does it make sense to make it the default?

**Comment by Rufflewind** [comment]
Do you know what happens if `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` is passed to a Windows system that doesn't support it?  It would be nice to have it by default, but I'm concerned about compatibility with older versions of Windows.

**Comment by YellPika** [comment]
[This thread](https://cygwin.com/ml/cygwin/2017-04/msg00305.html) claims that passing the flag on earlier builds of will give `ERROR_INVALID_PARAMETER`. This could be solved by checking at runtime for Windows 10 build >= 14972.

**Comment by Rufflewind** [comment]
I'll just check for the error code instead of the build number (which might be difficult on older versions of Windows).

**Comment by YellPika** [comment]
Thanks!

Could you elaborate on why there would be difficulties on earlier versions of Windows? If we're on anything before Windows 10 then we shouldn't even need to check the build number since this feature doesn't exist.

(Also, your last commit doesn't work for me. Did you mean to pass `flags .|. unpriv` to `c_CreateSymbolicLink`?)

**Comment by Rufflewind** [comment]
> Did you mean to pass `flags .|. unpriv` to `c_CreateSymbolicLink`?

Yes, my bad.  Please try 76e4c21a3db4b8851bd8369d2ca4bcaeb1bb9cb5 when you get the chance.

> If we're on anything before Windows 10 then we shouldn't even need to check the build number since this feature doesn't exist.

It's just a bit more involved to implement (and might involve more `#if`s).

**Comment by YellPika** [comment]
For some reason I can't pull that changeset. If I click on the link, I can browse the changes, but it's otherwise inaccessible.

In any case, I've applied the patch manually and can confirm that it works.

**Comment by Rufflewind** [comment]
> For some reason I can't pull that changeset.

It was still in my fork at the time: https://github.com/Rufflewind/directory

> In any case, I've applied the patch manually and can confirm that it works.

Yay!
