### ISSUE TITLE
Permissions for users other than the owner

### ISSUE THREAD

**Issue by siddharthist** [haskell/directory#86]
All permissions modification currently happens only for the owner. One of the predominant use-cases of file permissions is to *exclude* unauthorized users (generally, those other than the owner) from reading a file. Could this be added?

**Comment by Rufflewind** [comment]
Thanks for suggestion!  That sounds like a useful feature, but I'm afraid it's probably out of `directory`'s scope.  Even if it is, I imagine it would be quite tricky to implement in a cross platform way – the impedance mismatch between POSIX permissions and Windows ACLs is too big for a cross-platform library like `directory`.

Currently, permissions in `directory` are a bit of a hack.  They are designed with a POSIX interface and work fine on POSIX-like systems.  On Windows they do almost nothing.  Not great for a cross-platform library.  I'm pretty sure the only thing they're good for is modifying the "read-only" attribute and making things executable.

It's probably easier to use a different library for this kind of task.  For example, if you're only concerned about POSIX-like systems, [`unix`](https://hackage.haskell.org/package/unix-2.7.2.2/docs/System-Posix-Files.html) would work fine for this purpose!
