### ISSUE TITLE
getXdgDirectory ignores relative path in XDG_CACHE_HOME

### ISSUE THREAD

**Issue by Gabriel439** [haskell/directory#87]
`getXdgDirectory` uses the fallback path whenever the environment variable is a relative path:

https://github.com/haskell/directory/blob/19d6dc0d33366a8920bf8acc7a0fd3ef533d39c3/System/Directory/Internal/Posix.hsc#L295

However, this doesn't seem to match the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) as far as I can tell

**Comment by Rufflewind** [comment]
There seems to be different versions of the spec floating around.  [Version 0.8](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.8.html) says:

> All paths set in these environment variables must be absolute. If an implementation encounters a relative path in any of these variables it should consider the path invalid and ignore it.

I don't know which version is canonical.

**Comment by Gabriel439** [comment]
Oh, interesting.  It looks like that changed at some point, because it's missing from the latest version: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by Rufflewind** [comment]
I asked the XDG mailing list a while back but never got a response.  I'll assume `basedir-spec-latest.html` is the canonical version, as it's more prominently linked to than `basedir-spec-0.8.html`.

**Comment by phadej** [comment]
And now https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html is down.

https://specifications.freedesktop.org/ however has 

```
basedir-spec

version 0.7 (one page, split pages)
```

which says **All paths set in these environment variables must be absolute. If an implementation encounters a relative path in any of these variables it should consider the path invalid and ignore it.**

In https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
