### ISSUE TITLE
utimensat is broken on HFS+

### ISSUE THREAD

**Issue by Rufflewind** [haskell/directory#88]
Recent versions of OS X support `utimensat` but they seem to be buggy on HFS+: using the function to set the atime only (mtime = `UTIME_OMIT`) does not work as intended; it instead appears to set the atime to the current time.

Maybe we should just disable `utimensat` on OS X?

**Comment by llelf** [comment]
`utimensat` works fine for me (10.13.6).

**Comment by Rufflewind** [comment]
Can you elaborate on how you tested it?  (including how `utimensat` was called and on what kind of file system)

**Comment by Rufflewind** [comment]
I don't really know of a way to fix this without disabling utimensat entirely, which is not ideal.  It ought to be the upstream's responsibility to make sure their file system APIs function according to spec.

Marking as wontfix.
