### ISSUE TITLE
System.Directory.getPermissions does not work well on Windows 7

### ISSUE THREAD

**Issue by freizl** [haskell/directory#9]
It works well for following code

```
System.Directory.getPermissions "/path/to/somewhere"
```

However getting error with this:

```
System.Directory.getPermissions "/path/to/somewhere/"
*** Exception: getPermissions: does not exist (No such file or directory)
```

The only difference is the path name. It gets error when having extra trailing slash.
It looks wired.

Thanks your help.

PS: Previous discussion at https://ghc.haskell.org/trac/ghc/ticket/8342

**Comment by Rufflewind** [comment]
The distinction doesn't exist on Linux at least, since that's what `lstat` is for.

I'll just drop the trailing slashes on Windows, since arguably this is just them being necessarily picky.

**Comment by freizl** [comment]
:+1:
