### ISSUE TITLE
Unable to access directory while setting up a Haskell project locally

### ISSUE THREAD

**Issue by abiduzz420** [haskell/directory#91]
I am looking to set-up [Code World project](https://github.com/google/codeworld) on my local machine. I tried to run the installation process which has one of the dependencies as `haskell/directory.` The installation abruptly ends while trying to install the package. I am getting the following error stating that it is unable to clone the hackage: 
```
fatal: unable to access 'http://git.haskell.org/packages/directory.git/': Failed to connect to git.haskell.org port 80: Connection refused
Clone of 'http://git.haskell.org/packages/directory.git/' into submodule path 'boot/directory' failed
```
I have tried to run the `install.sh` script of the project twice, and on both occasions I have met with similar fate. I have raised my concern in project's community mailing list also. Please share your thoughts on whether this issue has anything do with the package itself.

Thank you :)

**Comment by chessai** [comment]
On first glance, this may have to do with needing to use SSH urls? Port 80 is used for HTTP, and it looks like your machine is refusing to make connections to port 80. 

I know @cdsmith isn't a big user of git so the http/https vs. ssh probably isn't a concern for him

**Comment by cdsmith** [comment]
Based on the fact that this is cloning into "boot/directory", I guess this is a problem booting GHCJS.  @luite may know what's up better than me.  But I'll try this, as well.  If GHCJS 8.0 installation is broken, it might be time to make the leap to 8.6

**Comment by Rufflewind** [comment]
Sorry, I don't think this is caused by anything within `directory`.  This seems more like an issue with the setup process -- perhaps the URL from which they are trying to download this package is out of date?

Please consider filing a bug upstream instead.  Thanks, and good luck!
