### ISSUE TITLE
Impossible to test for broken symbolic link without getting an exception 

### ISSUE THREAD

**Issue by DavidEichmann** [haskell/directory#94]
Observed on version 1.3.3.0

Given a path, it is impossible to test for broken link vs the path not existing without getting a "does not exist" exception in the "does not exist" case.

we have a few functions at our disposal:

| input path is a... | doesFileExist | doesDirectoryExist | doesPathExist | pathIsSymbolicLink |
|-|-|-|-|-|
| directory | False | True  | True | False
| file | True | False | True | False |  | 
| directory link | False |  True | True | True | 
| file link | True | False | True | True | 
| broken link | False | False | False | True |
| does not exist | False | False | False | Exception |

So in order to test between "broken link" and "does not exist" we must use pathIsSymbolicLink, but that will throw an exception. Is there a better way to do this? Alternatively, one can do their own existence test using `getDirectoryContents`, but that seems like a hack.

**Comment by Rufflewind** [comment]
I don't believe there's a better way to do it, but what's wrong with catching the exception?

```hs
r <- try (pathIsSymbolicLink p)
case r of
  Right True -> {- exists -}
  Right False -> {- not a symlink -}
  Left e | isDoesNotExistError e -> {- does not exist -}
         | otherwise -> throwIO e
```

**Comment by DavidEichmann** [comment]
It's generally bad practice to use Exceptions as a way of returning information. Exceptions should generally only be used for "unexpected" cases. E.g if `doesFileExist` threw an exception when the path didn't exist, that would not be convenient. Perhaps a function with a more consistent name would help here: `doesSymbolicLinkExist` such that:

| input path is a... | doesFileExist | doesDirectoryExist | doesPathExist | **doesSymbolicLinkExist** |
|-|-|-|-|-|
| directory | False | True  | True | **False** |
| file | True | False | True | **False** | 
| directory link | False |  True | True | **True** | 
| file link | True | False | True | **True** | 
| broken link | False | False | False | **True** |
| does not exist | False | False | False | **False** |

This seems like consistent naming and behaviour, though there is some subtlety here. Users may not expect this:

- Even if the path doesn't exist, it may still be a (broken) symbolic link
    `not (doesPathExist f) -/-> not (doesSymbolicLinkExist f)`
- If it's not a file nor a directory it may still be a (broken) symbolic link.
    `not (doesFileExist f) && not (doesDirectoryExist f)  -/-> not (doesSymbolicLinkExist f)`
- A symlink may be a chain of symlinks e.g. linkA -> linkB -> fileC. If fileC doesn't exist, then both linkA and linkB are broken, but the target of linkA still exists.
    `doesSymbolicLinkExist f && not (doesPathExist f)  -/-> not (doesPathExist (targetOfF))`

Unfortunately I think this is a an inherent complexity, so I wander what the best option is to minimize bugs and keep users happy. By default `doesFileExist`, `doesDirectoryExist`, and `doesPathExist` look through symlinks which is simple. We also don't want to change behavior (we don't want to break existing code). `doesSymbolicLinkExist` doesn't look through symlinks, but that is implied by the name any way. Clear indication of how these function work with symlinks and broken symlinks is important information that should be added to the documentation in any case.

**Comment by chessai** [comment]
Edited your comment: typo.

**Comment by Rufflewind** [comment]
The documentation could definitely be improved in this regard.  Feel free to point out any issues that you spot with the current docs.

With regards to the API, I'm not really convinced that testing for an exception is problematic in this context.  Files that don't exist is just one of many, many ways in which file system operations can fail, and using exceptions is the de facto convention for similar libraries.  Adding more functions would increase the API surface area even more and probably add to the confusion and complexity.

**Comment by tdammers** [comment]
@DavidEichmann you cannot avoid exception handling anyway due to the concurrent nature of filesystem access. Even if there were a way to do this properly, the following could still happen:

1. Program A tests whether symlink X is valid.
2. Symlink X is reported valid.
3. Program A decides to operate on the symlink.
4. Program B modifies the symlink, breaking it.
5. Program A operates on the now broken symlink, under the assumption that it is not broken.

I really don't see a way around throwing an exception in step 5, and dealing with it somehow in Program A.

The same concerns apply to almost all other file operations - you always have to be prepared to deal with filesystem changes occurring between your testing of a precondition and acting upon it. E.g. `doesFileExist fn >>= \exists -> if exists then readFile fn else pure "dummy data"` could raise a does-not-exist error, because someone might delete the file while you are busy evaluating the `if` expression.

**Comment by Rufflewind** [comment]
As noted in https://github.com/haskell/directory/issues/94#issuecomment-492417531 I think this is inherent to the existing design of this package.  File system operations can return a slew of different errors.

I do believe the `pathIsSymbolicLink` function can be better documented in regards to what potential errors it can return.

**Comment by hasufell** [comment]
I stumbled over this too, looking for an existing function and came up with this:

```hs
isBrokenSymlink :: FilePath -> IO Bool
isBrokenSymlink fp = do
  try (pathIsSymbolicLink fp) >>= \case
    Right True -> do
      let symDir = takeDirectory fp
      tfp <- getSymbolicLinkTarget fp
      not <$> doesPathExist
        -- this drops 'symDir' if 'tfp' is absolute
        (symDir </> tfp)
    Right b -> pure b
    Left e | isDoesNotExistError e -> pure False
           | otherwise -> throwIO e
```

Is this something worthwhile to add to the library? Of course it's not particularly atomic...

**Comment by Rufflewind** [comment]
The proper way to test whether a symbolic link is broken is to simply attempt to read it the way you had intended to, handling the `DoesNotExistError` as necessary. This avoids TOCTOU bugs and the need to emulate the OS-dependent behavior of interpreting the symbolic link's target.

In the rare case where you just want to present the brokenness to the user, `doesPathExist` can be used to dereference the symbolic link.

**Comment by hasufell** [comment]
> The proper way to test whether a symbolic link is broken is to simply attempt to read it the way you had intended to

I cannot follow. Can you be more concrete with code? If you attempt to simply read the file, you don't know whether it's a symlink in the first place.

**Comment by Rufflewind** [comment]
> If you attempt to simply read the file, you don't know whether it's a symlink in the first place, so you need two syscalls at least anyway.

That is true, but can you explain what use case requires knowing both (a) whether a path is a symbolic link and (b) whether the symbolic link points to a target that exists?

**Comment by hasufell** [comment]
> > If you attempt to simply read the file, you don't know whether it's a symlink in the first place, so you need two syscalls at least anyway.
> 
> That is true, but can you explain what use case requires knowing both (a) whether a path is a symbolic link and (b) whether the symbolic link points to a target that exists?

I use symlinks in ghcup similar to debians "alternatives" approach. The case of a stray symlink is very different from a non-existent file. Most of the time, I'm not opening the files, but reading the symbolic link target, parsing them and checking that the destination is healthy.

**Comment by Rufflewind** [comment]
> reading the symbolic link target, parsing them

As explained in https://github.com/haskell/directory/issues/94#issuecomment-846447350, attempting to emulate OS-specific logic is not recommended as a general practice.

That being said, if the symbolic links are *managed solely by your program* (as I would assume for ghcup and Debian alternatives), then it should be safe to assume that:

1. The symbolic link is, in fact, a symbolic link, and
2. The symbolic link target is an ordinary absolute path.

Under these assumptions, the most expedient option is to simply call `doesPathExist` to determine whether the link is broken. If there is uncertainty around assumption 1, one could also add `pathIsSymbolicLink` to be on the safe side.

**Comment by hasufell** [comment]
> As explained in #94 (comment), attempting to emulate OS-specific logic is not recommended as a general practice.

This is not OS-specific logic. I made this logic work on both Linux and Windows. And your suggestion in that comment is not sufficient.

> 
> That being said, if the symbolic links are _managed solely by your program_ (as I would assume for ghcup and Debian alternatives), then it should be safe to assume that:
> 
>     1. The symbolic link is, in fact, a symbolic link, and
> 
>     2. The symbolic link target is an ordinary absolute path.
> 
> 

These assumptions are incorrect for my use case.

1. It's possible the path is not a symbolic link to begin with, which triggers different program behavior
2. This can also not be assumed

I suggest we don't assume how programs use symbolic links and how their program behavior depends on them. Especially not in a low-level library.

**Comment by Rufflewind** [comment]
Sorry, there was an error in my response earlier with assumption 2. Assumption 2 isn't needed for `doesPathExist` to work.

To test the brokeness of a symbolic link, the following should be enough:

~~~haskell
(&&) <$> pathIsSymbolicLink path <*> doesPathExist path
~~~

This returns `True` if the path refers to a symbolic link *and* the link points to a valid and accessible target (either file or directory). You can replace `doesPathExist` with, say, `doesFileExist` if you instead want to restrict to only file targets.

The only (unavoidable) assumption that needs to be made here is that the symbolic link is not being modified concurrently.

**Comment by hasufell** [comment]
> Sorry, there was an error in my response earlier with assumption 2. Assumption 2 isn't needed for `doesPathExist` to work.
> 
> To test the brokeness of a symbolic link, the following should be enough:
> 
> ```haskell
> (&&) <$> pathIsSymbolicLink path <*> doesPathExist path
> ```

This doesn't deal with `isDoesNotExistError` exception as mentioned in previous comments... which indicates to me that it's worthwhile adding to this library. But I have no strong opinion on whether or not it belongs here.
