### ISSUE TITLE
XDG environment variables ignored on Windows

### ISSUE THREAD

**Issue by stkb** [haskell/directory#95]
`getXdgDirectory` would be a super-handy function, but on Windows all XDG environment variables are ignored in that function (which the documentation also isn't super-clear about), so the user can't customize the directories.

What's the reason for this? I noticed this was done in a682ebb9a1bbc99f598f15b59e4077a8afae891c but no reason given.

Thanks

**Comment by Rufflewind** [comment]
I don't remember the reason, but I don't really know what the ideal behavior is here either.  The intent of that function is to use what is most idiomatic on a given operating system, which for Windows is CSIDL_LOCAL_APPDATA / CSIDL_APPDATA, not the XDG standard, which Windows doesn't even attempt to conform.

**Comment by Rufflewind** [comment]
Do you need this feature on Windows?

**Comment by stkb** [comment]
Sorry, had been distracted by other things.

The function's defaults (AppData/LocalAppData) for Windows are good. But a Windows user should be able customize this if they want, to have a more Linux/XDG standard-like setup; naturally with the environment variables.

Other programs support these variables on Windows, and I would very much appreciate it if this function also did, as it would greatly simplify the settings-finding code in the program I'm working on.

**Comment by stkb** [comment]
Fantastic, Thanks!
