### ISSUE TITLE
Consider a variant of deleteFile that on Windows retries x times before giving up

### ISSUE THREAD

**Issue by Mistuke** [haskell/directory#96]
As discussed in https://github.com/haskell/hsc2hs/pull/25 there are various services on Windows that can keep a file open for a fraction of time, such as indexer or AV services.  That means that `deleteFile` may fail temporarily.

It's a reasonably common idiom, SQLlite for instance does so as well https://www.sqlite.org/src/info/89f1848d7f and we do it in the GHC testsuite and now hsc2hs to avoid a race condition with the file deletion.

Would it be perhaps handy to have such a function in Directory?

**Comment by Rufflewind** [comment]
It's not a very elegant solution, but I guess it's kind of needed on Windows.  I would suggest making a somewhat generic retry function if possible, as there are many variants of `removeFileThing`:

```hs
retryOnPermissionError :: {- numRetries -} Int -> IO a -> IO a
```

**Comment by Rufflewind** [comment]
Is there still interest in this feature?

**Comment by Mistuke** [comment]
> Is there still interest in this feature?

Yes, it's used in GHC, hsc2hs, cabal and GHC's testsuite. So it would allow us to align those implementations and I believe it's useful for third parties as well.  But I honestly don't know when I would personally have the time to implement this.

**Comment by hasufell** [comment]
> retryOnPermissionError :: {- numRetries -} Int -> IO a -> IO a

I think the wording is problematic. Afais, the exceptions to retry on are `ERROR_LOCK_VIOLATION` and `ERROR_SHARING_VIOLATION`, which are very specific. And we don't know if that will change or if there are more use cases for this for some users.

I would go so far to say this doesn't belong in this library, but is a generic exception handling function and already exists in various forms, such as [retryBool](https://hackage.haskell.org/package/extra-1.6.18/docs/Control-Exception-Extra.html#v:retryBool).

The documentation of `removeFile` should simply document this behavior. That's what the python sdtlib [does](https://docs.python.org/3/library/os.html#os.remove) as well.

**Comment by Rufflewind** [comment]
I'm inclined to agree with @hasufell that this might be getting a bit out of scope for this library. A general retry function probably belongs to `System.IO.Exception` or similar.

Closing this issue for now. Let me know if there are any concerns.

**Comment by Rufflewind** [comment]
It looks like there's an algorithm for deleting directories on Windows without the need for retries: #110
